version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build
      - chmod +x test.sh
      - ./test.sh

artifacts:
  files:
    - "**/*"
  base-directory: "build"
