version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build
      - chmod +x test.sh
      - chmod +x input.txt
      - ls -l
      - zip -r input.txt output.zip

artifacts:
  files:
    - "**/*"
  base-directory: "build" # フロントの成果物
  discard-paths: yes # ディレクトリ構造を保持せず、ファイルを直下に出力
