version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build
      - chmod +x test.sh
      - ls -l
      - ./test.sh  # test.sh を実行

artifacts:
  files:
    - "**/*"
  base-directory: "build"  # フロントの成果物
  discard-paths: yes  # ディレクトリ構造を保持せず、ファイルを直下に出力

  # test.sh の出力ファイルもアーティファクトとして含める
  - "output.zip"
