version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build
      - chmod +x test.sh
      - chmod +x input.txt
      - ls -l
      - cp input.txt copy_of_file.txt

artifacts:
  files:
    - build/**/* # buildフォルダ内の全ファイル
    - copy_of_file.txt # 追加した行
  base-directory: "." # ルートディレクトリを指定
